import type {
  Project,
  ProjectMilestone,
  SubsidyDocument,
  PaymentMilestoneItem,
  MaterialItem,
} from '@/shared/lib/types/project';

export const DEFAULT_INSTALLATION_MILESTONES: ProjectMilestone[] = [
  {
    id: 1,
    title: 'Material procurement confirmed',
    completed: true,
    status: 'Done',
    proofUrl: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=600&auto=format&fit=crop&q=80',
    proofFileName: 'procurement_invoice_po_8841.pdf',
    proofUploadedAt: '12 May 2026',
    description: 'PO generated for 3kW Tier-1 Mono PERC panels and 3.3kW inverter.',
  },
  {
    id: 2,
    title: 'Material delivered to site',
    completed: true,
    status: 'Done',
    description: 'All BOS and PV modules safely received and verified on-site.',
  },
  {
    id: 3,
    title: 'Structure and panel installation complete',
    completed: true,
    status: 'Done',
    description: 'Elevated HDG mounting structure erected and modules bolted.',
  },
  {
    id: 4,
    title: 'Inverter and wiring complete',
    completed: false,
    status: 'Pending',
    description: 'ACDB/DCDB boxes, inverter installation, and earthing pits connection.',
  },
  {
    id: 5,
    title: 'Testing and commissioning complete',
    completed: false,
    status: 'Pending',
    description: 'Voltage/amperage string testing and inverter no-load trial run.',
  },
  {
    id: 6,
    title: 'DISCOM inspection application submitted',
    completed: false,
    status: 'Pending',
    description: 'Form filed on state electricity board portal with single line diagram.',
  },
  {
    id: 7,
    title: 'DISCOM inspection passed',
    completed: false,
    status: 'Pending',
    description: 'Utility engineer physical site inspection and clearance certificate.',
  },
  {
    id: 8,
    title: 'Net meter installed',
    completed: true,
    status: 'Done',
    description: 'Bidirectional utility meter installed and grid synchronization active.',
  },
];

export const DEFAULT_SUBSIDY_DOCUMENTS: SubsidyDocument[] = [
  {
    id: 'doc-1',
    title: 'Aadhar Card',
    uploaded: true,
    fileName: 'aadhar_card_arun_sharma.pdf',
    fileUrl: '#',
    uploadedAt: '15 May 2026',
  },
  {
    id: 'doc-2',
    title: 'Electricity Bill',
    uploaded: true,
    fileName: 'latest_electricity_bill_mumbai.pdf',
    fileUrl: '#',
    uploadedAt: '16 May 2026',
  },
  {
    id: 'doc-3',
    title: 'Property Proof',
    uploaded: true,
    fileName: 'property_tax_receipt_2026.pdf',
    fileUrl: '#',
    uploadedAt: '18 May 2026',
  },
  {
    id: 'doc-4',
    title: 'Bank Passbook',
    uploaded: false,
  },
  {
    id: 'doc-5',
    title: 'Installation Certificate',
    uploaded: false,
  },
  {
    id: 'doc-6',
    title: 'Inspection Report',
    uploaded: false,
  },
];

export const DEFAULT_PAYMENT_MILESTONES: PaymentMilestoneItem[] = [
  {
    id: 'pm-1',
    milestone: 'Delivery Payment',
    amountDue: 110550,
    dueDate: '06 Jul 2026',
    status: 'Partially Received',
    receivedAmount: 10000,
  },
  {
    id: 'pm-2',
    milestone: 'Advance / Booking Payment',
    amountDue: 44220,
    dueDate: '15 May 2026',
    status: 'Received',
    receivedAmount: 44220,
  },
  {
    id: 'pm-3',
    milestone: 'Structure & Panel Installation',
    amountDue: 44220,
    dueDate: '20 Jul 2026',
    status: 'Partially Received',
    receivedAmount: 12110,
  },
  {
    id: 'pm-4',
    milestone: 'Net Metering & Commissioning',
    amountDue: 22110,
    dueDate: '10 Aug 2026',
    status: 'Pending',
    receivedAmount: 0,
  },
];

export const DEFAULT_MATERIALS: MaterialItem[] = [
  {
    id: 'mat-1',
    name: '540W Mono PERC Half-Cut Solar Panels',
    quantity: 6,
    unit: 'Units',
    specification: 'Tier-1 High-Efficiency Bifacial',
    status: 'Delivered',
  },
  {
    id: 'mat-2',
    name: '3.3 kW Single Phase On-Grid Inverter',
    quantity: 1,
    unit: 'Unit',
    specification: 'Dual MPPT, IP65 with Wi-Fi Logger',
    status: 'Delivered',
  },
  {
    id: 'mat-3',
    name: 'Elevated HDG Mounting Structure',
    quantity: 1,
    unit: 'Set',
    specification: 'Hot Dip Galvanized 80 Microns, Wind 150 km/h',
    status: 'Installed',
  },
  {
    id: 'mat-4',
    name: 'ACDB & DCDB Distribution Box with SPD/MCB',
    quantity: 1,
    unit: 'Set',
    specification: 'IP65 Enclosure, Type 2 SPD, Havells MCB',
    status: 'Delivered',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'Arun Sharma - 3kW - 2026',
    customerName: 'Arun Sharma',
    status: 'In Progress',
    projectManager: 'Unassigned',
    systemCapacity: '3.0 kW System',
    location: 'Mumbai, Maharashtra',
    cost: 221100,
    totalReceived: 66330,
    balanceOutstanding: 154770,
    completedMilestones: 4,
    totalMilestones: 8,
    milestones: DEFAULT_INSTALLATION_MILESTONES,
    subsidyDocuments: DEFAULT_SUBSIDY_DOCUMENTS,
    paymentMilestones: DEFAULT_PAYMENT_MILESTONES,
    materials: DEFAULT_MATERIALS,
    createdAt: '2026-02-14',
    notes: 'Structure work scheduled for completion this week.',
  },
  {
    id: 'proj-2',
    name: 'Rahul Desai - 3kW - 2026',
    customerName: 'Rahul Desai',
    status: 'In Progress',
    projectManager: 'Unassigned',
    systemCapacity: '3.0 kW System',
    location: 'Pune, Maharashtra',
    cost: 221100,
    totalReceived: 22110,
    balanceOutstanding: 198990,
    completedMilestones: 0,
    totalMilestones: 8,
    milestones: DEFAULT_INSTALLATION_MILESTONES.map((m) => ({
      ...m,
      completed: false,
      status: 'Pending' as const,
      proofUrl: undefined,
      proofFileName: undefined,
    })),
    subsidyDocuments: DEFAULT_SUBSIDY_DOCUMENTS.map((doc, idx) => ({
      ...doc,
      uploaded: idx === 0, // only aadhar uploaded
    })),
    paymentMilestones: DEFAULT_PAYMENT_MILESTONES.map((pm, idx) => ({
      ...pm,
      status: idx === 1 ? 'Partially Received' : 'Pending',
      receivedAmount: idx === 1 ? 22110 : 0,
    })),
    materials: DEFAULT_MATERIALS,
    createdAt: '2026-02-18',
    notes: 'Awaiting site survey schedule confirmation from customer.',
  },
  {
    id: 'proj-3',
    name: 'Vikram Patel - 5kW - 2026',
    customerName: 'Vikram Patel',
    status: 'In Progress',
    projectManager: 'Rajesh Kumar',
    systemCapacity: '5.0 kW System',
    location: 'Thane, Maharashtra',
    cost: 345000,
    totalReceived: 200000,
    balanceOutstanding: 145000,
    completedMilestones: 5,
    totalMilestones: 8,
    milestones: DEFAULT_INSTALLATION_MILESTONES.map((m, idx) => ({
      ...m,
      completed: idx < 5,
      status: idx < 5 ? ('Done' as const) : ('Pending' as const),
    })),
    subsidyDocuments: DEFAULT_SUBSIDY_DOCUMENTS.map((d, idx) => ({
      ...d,
      uploaded: idx < 4,
    })),
    paymentMilestones: DEFAULT_PAYMENT_MILESTONES,
    materials: DEFAULT_MATERIALS,
    createdAt: '2026-01-28',
  },
  {
    id: 'proj-4',
    name: 'Priya Kulkarni - 10kW - 2026',
    customerName: 'Priya Kulkarni',
    status: 'Completed',
    projectManager: 'Priya Sharma',
    systemCapacity: '10.0 kW System',
    location: 'Navi Mumbai, Maharashtra',
    cost: 680000,
    totalReceived: 680000,
    balanceOutstanding: 0,
    completedMilestones: 8,
    totalMilestones: 8,
    milestones: DEFAULT_INSTALLATION_MILESTONES.map((m) => ({
      ...m,
      completed: true,
      status: 'Done' as const,
    })),
    subsidyDocuments: DEFAULT_SUBSIDY_DOCUMENTS.map((d) => ({
      ...d,
      uploaded: true,
    })),
    paymentMilestones: DEFAULT_PAYMENT_MILESTONES.map((p) => ({
      ...p,
      status: 'Received',
      receivedAmount: p.amountDue,
    })),
    materials: DEFAULT_MATERIALS,
    createdAt: '2026-01-10',
  },
];
